#!/home/voldemort/.nvm/versions/node/v16.15.0/bin/node

const chalk = require("chalk");
const { createHmac } = require("crypto");
const yargs = require("yargs");

yargs.option("show", {
  alias: "s",
  description: "Should show the Hash in on Terminal",
  type: "boolean",
  default: false,
});

yargs.option("algorithm", {
  alias: "a",
  description: "What Algorithm to use (default sha256)",
  choices: ["sha256", "md5", "sha512", "sha3-512"],
  default: "sha256",
});

yargs.help();

yargs.alias("help", "h").argv;

const { show, algorithm, _ } = yargs.argv;
const [password, update] = _;

async function main({
  password,
  update = "",
  show = false,
  algorithm = "sha256",
}) {
  if (!password) {
    console.log(chalk.red("[ ERROR ] Password is required"));
    process.exit(127);
  }

  const hash = createHmac(algorithm, password).update(update).digest("hex");
  const hidden = hash.substring(0, 10) + "*".repeat(10);

  console.log(chalk.bold.cyan(`[ HASH ] ${show ? hash : hidden}`));

  const { default: clipboard } = await import("clipboardy");
  await clipboard.write(hash);

  console.log(chalk.bold.green("[ INFO ] Copied to Clipboard"));
}

main({ password, update, show, algorithm });
